/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProofChain } from "./ProofChain";
export * as factories from "./factories";
export { ProofChain__factory } from "./factories/ProofChain__factory";
